name: fitsaga
description: A cross-platform mobile app for gym management with role-based access, session booking, and tutorial features integrated with Firebase.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  skeletons: ^0.0.3
  
  # Video
  video_player: ^2.8.2
  
  # Data
  http: ^1.1.2
  equatable: ^2.0.5
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env